[cases]
[cases.caesar.dec]
inp = '-dk 13 Gur dhvpx oebja sbk whzcf bire gur ynml qbt.'
out = "The quick brown fox jumps over the lazy dog.\n"
[cases.caesar.enc]
inp = '-k 13 The quick brown fox jumps over the lazy dog.'
out = "Gur dhvpx oebja sbk whzcf bire gur ynml qbt.\n"

[progs]
caesar = ['py']

[langs]
python = 'py'
